[weblinks]
inspire500 = "https://daten.gdz.bkg.bund.de/produkte/sonstige/geogitter/aktuell/DE_Grid_ETRS89-LAEA_500m.gpkg.zip"
inspire1k  = "https://daten.gdz.bkg.bund.de/produkte/sonstige/geogitter/aktuell/DE_Grid_ETRS89-LAEA_1km.gpkg.zip"
inspire5k  = "https://daten.gdz.bkg.bund.de/produkte/sonstige/geogitter/aktuell/DE_Grid_ETRS89-LAEA_5km.gpkg.zip"

osmGermany = "https://download.geofabrik.de/europe/germany-latest.osm.pbf"

gtfsGermany = "https://download.gtfs.de/germany/free/latest.zip"

