# Notes:
# This calibration is from the 2023 paper:
# OMOD: An open-source tool for creating disaggregated mobility demand based on OpenStreetMap
# The mode choice parameter are from the 2025 paper:
# Transport Mode Choice for Disaggregated Mobility Demand Generation

[inheritance]
parent = "" # Define the ancestor of this calibration from which all not specified parameters should be taken.